---
- name: Copy over audit policy file
  copy:
    src: files/k8s_audit_poliicy.yaml
    dest: /etc/kubernetes/audit-policy.yaml

- name: Create audit log directory if it does not exist
  file:
    path: /var/log/kubernetes/audit
    state: directory
    mode: "0755"
