---
- name: Enable br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Enable net.bridge.bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_set: yes
    reload: yes

- name: Enable net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    reload: yes
