---
- name: Install kubelet, kubeadm, kubectl
  yum:
    name: ["kubeadm", "kubelet", "kubectl"]
    state: latest
    disable_excludes: kubernetes

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
