---
- name: Configure Kubernetes Masters Baselines
  hosts: kubernetesMasterNodes
  gather_facts: True
  become: true

  tasks:
    - name: Install/Update/Enable FirewallD
      include: ./shared/centos_install_firewalld.yaml

    - name: Configure FirewallD for Masters
      include: ./master/configure_firewalld.yaml

    - name: Configure K8s and Docker Repos
      include: ./shared/centos_repos.yaml

    - name: Set Kubernetes Audit Policy assets
      include: ./master/create_audit_policy.yaml

    - name: Install Docker
      include: ./shared/centos_install_docker.yaml

    - name: Install Kubernetes
      include: ./shared/centos_install_k8s_pkgs.yaml

    - name: Copy over Cluster Configuration YAML
      include: ./master/create_cluster_config.yaml
